# Generated by Django 2.2.5 on 2019-10-05 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0002_auto_20191005_0545'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmeduser',
            name='confirm',
            field=models.BooleanField(verbose_name='Пользователь подтвержден'),
        ),
    ]
