# Generated by Django 2.2.5 on 2019-10-05 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0003_auto_20191005_1125'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmeduser',
            name='confirm',
            field=models.BooleanField(default=False, verbose_name='Пользователь подтвержден'),
        ),
        migrations.AlterField(
            model_name='confirmeduser',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='email address'),
        ),
    ]
