# Generated by Django 2.2.5 on 2019-10-05 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_auth', '0004_auto_20191005_1128'),
    ]

    operations = [
        migrations.AlterField(
            model_name='confirmeduser',
            name='email',
            field=models.EmailField(max_length=128, verbose_name='Email пользователя'),
        ),
    ]
